/**
 * Ranked Iranian film pool. Assign difficulty manually, then sync to movies.ts.
 *
 * Regenerate raw candidates: npm run fetch-candidates
 */

export interface MovieSeed {
  title: string
  year: number
  difficulty: 'easy' | 'medium' | 'hard'
  aliases?: string[]
}

export const MOVIES: MovieSeed[] = [
  // ---------- EASY ----------
  { title: 'A Separation', year: 2011, difficulty: 'easy', aliases: ['جدایی نادر از سیمین'] },
  { title: 'Children of Heaven', year: 1997, difficulty: 'easy', aliases: ['بچههای آسمان'] },
  { title: 'Muhammad: The Messenger of God', year: 2015, difficulty: 'easy', aliases: ['محمد'] },
  { title: 'The Lizard', year: 2004, difficulty: 'easy', aliases: ['مارمولک'] },
  { title: 'Intoxicated by Love', year: 2024, difficulty: 'easy', aliases: ['مست عشق'] },
  { title: 'Damascus Time', year: 2018, difficulty: 'easy', aliases: ['به وقت شام'] },
  { title: 'A Cube of Sugar', year: 2011, difficulty: 'easy', aliases: ['یه حبه قند'] },
  { title: 'Leila', year: 1997, difficulty: 'easy', aliases: ['لیلا'] },
  { title: 'The Fireworks Wednesday', year: 2006, difficulty: 'easy', aliases: ['چهارشنبهسوری'] },
  { title: "Leila's Brothers", year: 2022, difficulty: 'easy', aliases: ['برادران لیلا'] },
  { title: 'Just 6.5', year: 2019, difficulty: 'easy', aliases: ['متری شیش و نیم'] },
  { title: 'Mim Mesle Madar', year: 2006, difficulty: 'easy', aliases: ['میم مثل مادر'] },
  { title: 'The Book of Law', year: 2009, difficulty: 'easy', aliases: ['کتاب قانون'] },
  { title: 'The Elephant King', year: 2017, difficulty: 'easy', aliases: ['فیلشاه'] },
  { title: 'The Willow Tree', year: 2005, difficulty: 'easy', aliases: ['بید مجنون'] },
  { title: 'When the Moon Was Full', year: 2019, difficulty: 'easy', aliases: ['شبی که ماه کامل شد'] },
  { title: 'Bodyguard', year: 2016, difficulty: 'easy', aliases: ['بادیگارد'] },
  { title: 'Dayereh Zangi', year: 2008, difficulty: 'easy', aliases: ['دایره زنگی'] },
  { title: 'Ekhrajiha', year: 2007, difficulty: 'easy', aliases: ['اخراجیها'] },
  { title: 'From Karkheh to Rhein', year: 1993, difficulty: 'easy', aliases: ['از کرخه تا راین'] },
  { title: 'No Men Allowed', year: 2011, difficulty: 'easy', aliases: ['ورود آقایان ممنوع'] },
  { title: 'Notoriety', year: 2013, difficulty: 'easy', aliases: ['فیلم رسوایی'] },
  { title: 'Standing in the mist', year: 2016, difficulty: 'easy', aliases: ['ایستاده در غبار'] },
  { title: 'The Fateful Day', year: 1995, difficulty: 'easy', aliases: ['روز واقعه'] },
  { title: 'Two Women', year: 1999, difficulty: 'easy', aliases: ['دو زن'] },
  { title: 'Felicity Land', year: 2011, difficulty: 'easy', aliases: ['سعادتآباد'] },
  { title: 'Santouri', year: 2007, difficulty: 'easy', aliases: ['سنتوری'] },
  { title: 'Leily Is with Me', year: 1996, difficulty: 'easy', aliases: ['لیلی با من است'] },
  { title: 'Lottery', year: 2006, difficulty: 'easy', aliases: ['لاتاری'] },
  { title: 'Sperm Whale', year: 2015, difficulty: 'easy', aliases: ['نهنگ عنبر'] },
  { title: 'Sperm Whale 2', year: 2017, difficulty: 'easy', aliases: ['نهنگ عنبر ۲'] },
  { title: 'The Tenants', year: 1986, difficulty: 'easy', aliases: ['مستأجران'] },
  { title: 'The Warden', year: 2019, difficulty: 'easy', aliases: ['سرخپوست'] },
  { title: 'World, Hold on to Me', year: 2016, difficulty: 'easy', aliases: ['جهان با من برقص'] },

  // ---------- MEDIUM ----------
  { title: 'The Salesman', year: 2016, difficulty: 'medium', aliases: ['فروشنده'] },
  { title: 'Taxi', year: 2015, difficulty: 'medium', aliases: ['تاکسی'] },
  { title: "Where is the Friend's Home?", year: 1987, difficulty: 'medium', aliases: ['خانه دوست کجاست؟'] },
  { title: 'About Elly', year: 2009, difficulty: 'medium', aliases: ['درباره الی'] },
  { title: 'The Color of Paradise', year: 1999, difficulty: 'medium', aliases: ['رنگ خدا'] },
  { title: 'A Hero', year: 2021, difficulty: 'medium', aliases: ['قهرمان'] },
  { title: 'Baran', year: 2001, difficulty: 'medium', aliases: ['باران'] },
  { title: 'Offside', year: 2006, difficulty: 'medium', aliases: ['آفساید'] },
  { title: 'The Song of Sparrows', year: 2008, difficulty: 'medium', aliases: ['آواز گنجشکها'] },
  { title: 'The Cow', year: 1969, difficulty: 'medium', aliases: ['گاو'] },
  { title: 'Qeysar', year: 1969, difficulty: 'medium', aliases: ['قیصر'] },
  { title: 'Saint Mary', year: 2001, difficulty: 'medium', aliases: ['مریم مقدس'] },
  { title: 'Sun Children', year: 2020, difficulty: 'medium', aliases: ['خورشید'] },
  { title: 'The Kingdom of Solomon', year: 2010, difficulty: 'medium', aliases: ['ملک سلیمان'] },
  { title: 'Facing Mirrors', year: 2011, difficulty: 'medium', aliases: ['آینههای روبرو'] },
  { title: 'A Dragon Arrives!', year: 2016, difficulty: 'medium', aliases: ['اژدها وارد میشود!'] },
  { title: "I'm Taraneh, 15", year: 2002, difficulty: 'medium', aliases: ['من ترانه ۱۵ سال دارم'] },
  { title: 'No Date, No Signature', year: 2019, difficulty: 'medium', aliases: ['بدون تاریخ، بدون امضا'] },
  { title: 'Sara', year: 1993, difficulty: 'medium', aliases: ['سارا'] },
  { title: 'The Cycle', year: 1975, difficulty: 'medium', aliases: ['دایره مینا'] },
  { title: 'The Runner', year: 1984, difficulty: 'medium', aliases: ['دونده'] },
  { title: 'Dar Emtedade Shab', year: 1977, difficulty: 'medium', aliases: ['در امتداد شب'] },
  { title: 'Princess of Rome', year: 2015, difficulty: 'medium', aliases: ['شاهزاده روم'] },
  { title: 'The Beautiful City', year: 2004, difficulty: 'medium', aliases: ['شهر زیبا'] },
  { title: 'World War III', year: 2022, difficulty: 'medium', aliases: ['جنگ جهانی سوم'] },
  { title: 'Dar Aghooshe Derakht', year: 2023, difficulty: 'medium', aliases: ['در آغوش درخت'] },
  { title: 'Hamoun', year: 1990, difficulty: 'medium', aliases: ['هامون'] },
  { title: 'Kamalolmolk', year: 1984, difficulty: 'medium', aliases: ['کمالالملک'] },
  { title: 'Killing a Traitor', year: 2022, difficulty: 'medium', aliases: ['خائنکشی'] },
  { title: 'Killing Mad Dogs', year: 2001, difficulty: 'medium', aliases: ['سگکشی'] },
  { title: 'Life And A Day', year: 2014, difficulty: 'medium', aliases: ['ابد و یک روز'] },
  { title: 'The Blue-Veiled', year: 1995, difficulty: 'medium', aliases: ['روسری آبی'] },
  { title: 'The Night', year: 2020, difficulty: 'medium', aliases: ['آن شب'] },
  { title: 'The Painting Pool', year: 2013, difficulty: 'medium', aliases: ['حوض نقاشی'] },
  { title: 'Yalda, a Night for Forgiveness', year: 2019, difficulty: 'medium', aliases: ['یلدا'] },
  { title: 'Here Without Me', year: 2011, difficulty: 'medium', aliases: ['اینجا بدون من'] },
  { title: 'Lantouri', year: 2016, difficulty: 'medium', aliases: ['لانتوری'] },
  { title: 'Marriage, Iranian Style', year: 2006, difficulty: 'medium', aliases: ['ازدواج به سبک ایرانی'] },
  { title: 'The Low Heights', year: 2002, difficulty: 'medium', aliases: ['ارتفاع پست'] },
  { title: 'The Survivor', year: 1994, difficulty: 'medium', aliases: ['بازمانده'] },
  { title: 'The Girl in the Sneakers', year: 1998, difficulty: 'medium', aliases: ['دختری با کفشهای کتانی'] },
  { title: 'Pari', year: 1994, difficulty: 'medium', aliases: ['پری'] },
  { title: 'Snake Fang', year: 1990, difficulty: 'medium', aliases: ['دندان مار'] },
  { title: 'Tangsir', year: 1973, difficulty: 'medium', aliases: ['تنگسیر'] },
  { title: 'The Paternal House', year: 2012, difficulty: 'medium', aliases: ['خانه پدری'] },

  // ---------- HARD ----------
  { title: 'Taste of Cherry', year: 1997, difficulty: 'hard', aliases: ['طعم گیلاس'] },
  { title: 'It Was Just an Accident', year: 2025, difficulty: 'hard', aliases: ['یک تصادف ساده'] },
  { title: 'The Seed of the Sacred Fig', year: 2024, difficulty: 'hard', aliases: ['دانه انجیر مقدس'] },
  { title: 'Turtles Can Fly', year: 2004, difficulty: 'hard', aliases: ['لاکپشتها هم پرواز میکنند'] },
  { title: 'Certified Copy', year: 2010, difficulty: 'hard', aliases: ['کپی برابر اصل'] },
  { title: 'Close-Up', year: 1990, difficulty: 'hard', aliases: ['کلوزآپ'] },
  { title: 'The Circle', year: 2000, difficulty: 'hard', aliases: ['دایره'] },
  { title: 'The Wind Will Carry Us', year: 1999, difficulty: 'hard', aliases: ['باد ما را خواهد برد'] },
  { title: 'A Time for Drunken Horses', year: 2000, difficulty: 'hard', aliases: ['زمانی برای مستی اسبها'] },
  { title: 'Kandahar', year: 2001, difficulty: 'hard', aliases: ['سفر قندهار'] },
  { title: 'The White Balloon', year: 1994, difficulty: 'hard', aliases: ['بادکنک سفید'] },
  { title: 'There Is No Evil', year: 2020, difficulty: 'hard', aliases: ['شیطان وجود ندارد'] },
  { title: 'Through the Olive Trees', year: 1994, difficulty: 'hard', aliases: ['زیر درختان زیتون'] },
  { title: 'Blackboards', year: 2000, difficulty: 'hard', aliases: ['تخته سیاه'] },
  { title: 'Three Faces', year: 2018, difficulty: 'hard', aliases: ['سه رخ'] },
  { title: 'Gabbeh', year: 1996, difficulty: 'hard', aliases: ['گبه'] },
  { title: 'A Moment of Innocence', year: 1996, difficulty: 'hard', aliases: ['نون و گلدون'] },
  { title: 'Life, and Nothing More...', year: 1992, difficulty: 'hard', aliases: ['زندگی و دیگر هیچ'] },
  { title: 'No One Knows About Persian Cats', year: 2009, difficulty: 'hard', aliases: ['کسی از گربههای ایرانی خبر نداره'] },
  { title: 'Ten', year: 2002, difficulty: 'hard', aliases: ['ده'] },
  { title: 'The Cyclist', year: 1987, difficulty: 'hard', aliases: ['بایسیکلران'] },
  { title: 'Half Moon', year: 2006, difficulty: 'hard', aliases: ['نیوهمانگ'] },
  { title: 'My Favourite Cake', year: 2024, difficulty: 'hard', aliases: ['کیک محبوب من'] },
  { title: 'The Apple', year: 1998, difficulty: 'hard', aliases: ['سیب'] },
  { title: 'Rhino Season', year: 2012, difficulty: 'hard', aliases: ['فصل کرگدن'] },
  { title: 'The Silence', year: 1998, difficulty: 'hard', aliases: ['سکوت'] },
  { title: 'Closed Curtain', year: 2013, difficulty: 'hard', aliases: ['پرده'] },
  { title: 'Crimson Gold', year: 2003, difficulty: 'hard', aliases: ['طلای سرخ'] },
  { title: 'No Bears', year: 2022, difficulty: 'hard', aliases: ['خرس نیست'] },
  { title: 'The Mirror', year: 1997, difficulty: 'hard', aliases: ['آینه'] },
  { title: 'A Man of Integrity', year: 2017, difficulty: 'hard', aliases: ['لرد'] },
  { title: 'Ballad of a White Cow', year: 2020, difficulty: 'hard', aliases: ['قصیده گاو سفید'] },
  { title: 'Shirin', year: 2008, difficulty: 'hard', aliases: ['شیرین'] },
  { title: 'Bashu, the Little Stranger', year: 1989, difficulty: 'hard', aliases: ['باشو، غریبهٔ کوچک'] },
  { title: 'The Pig', year: 2018, difficulty: 'hard', aliases: ['خوک'] },
  { title: 'Today', year: 2014, difficulty: 'hard', aliases: ['امروز'] },
  { title: 'A Few Cubic Meters of Love', year: 2014, difficulty: 'hard', aliases: ['چند متر مکعب عشق'] },
  { title: 'Café Transit', year: 2005, difficulty: 'hard', aliases: ['کافه ترانزیت'] },
  { title: 'Homework', year: 1989, difficulty: 'hard', aliases: ['مشق شب'] },
  { title: 'Nahid', year: 2015, difficulty: 'hard', aliases: ['ناهید'] },
  { title: 'Once Upon a Time, Cinema', year: 1992, difficulty: 'hard', aliases: ['ناصرالدینشاه آکتور سینما'] },
  { title: 'Parting', year: 2016, difficulty: 'hard', aliases: ['رفتن'] },
  { title: 'Pedar', year: 1996, difficulty: 'hard', aliases: ['پدر'] },
  { title: 'Secret Ballot', year: 2001, difficulty: 'hard', aliases: ['رأی مخفی'] },
  { title: 'Under the Moonlight', year: 2001, difficulty: 'hard', aliases: ['زیر نور ماه'] },
  { title: 'Breath', year: 2016, difficulty: 'hard', aliases: ['نفس'] },
  { title: 'Hajji Washington', year: 1982, difficulty: 'hard', aliases: ['حاجی واشنگتن'] },
  { title: 'Iron Island', year: 2005, difficulty: 'hard', aliases: ['جزیره آهنی'] },
  { title: 'Khomreh', year: 1992, difficulty: 'hard', aliases: ['خمره'] },
  { title: 'Krystal', year: 2017, difficulty: 'hard', aliases: ['کریستال (فیلم)'] },
  { title: 'Terrestrial Verses', year: 2023, difficulty: 'hard', aliases: ['آیههای زمینی'] },
  { title: 'The Actor', year: 1993, difficulty: 'hard', aliases: ['هنرپیشه'] },
  { title: 'The Hunter', year: 2010, difficulty: 'hard', aliases: ['شکارچی (فیلم)'] },
  { title: 'The Marriage of the Blessed', year: 1988, difficulty: 'hard', aliases: ['عروسی خوبان'] },
  { title: 'The Pear Tree', year: 1998, difficulty: 'hard', aliases: ['درخت گلابی'] },
  { title: 'A Wedding Suit', year: 1976, difficulty: 'hard', aliases: ['لباسی برای عروسی'] },
  { title: 'Adobe and Mirror', year: 1966, difficulty: 'hard', aliases: ['خشت و آینه'] },
  { title: 'Baduk', year: 1992, difficulty: 'hard', aliases: ['بدوک'] },
  { title: 'Beyond the Wall', year: 2022, difficulty: 'hard', aliases: ['شب، داخلی، دیوار'] },
  { title: 'Deep Breath', year: 2003, difficulty: 'hard', aliases: ['نفس عمیق'] },
  { title: 'Hit the Road', year: 2021, difficulty: 'hard', aliases: ['جاده خاکی'] },
  { title: 'Hussein Who Said No', year: 2014, difficulty: 'hard', aliases: ['رستاخیز'] },
  { title: "Manuscripts Don't Burn", year: 2013, difficulty: 'hard', aliases: ['دستنوشتهها نمیسوزند'] },
  { title: 'Subtraction', year: 2022, difficulty: 'hard', aliases: ['تفریق'] },
  { title: 'The Night Bus', year: 2007, difficulty: 'hard', aliases: ['اتوبوس شب'] },
  { title: 'Until Tomorrow', year: 2022, difficulty: 'hard', aliases: ['تا فردا'] },
  { title: 'Woman and Child', year: 2025, difficulty: 'hard', aliases: ['زن و بچه'] },
  { title: 'A Walk in the Fog', year: 2011, difficulty: 'hard', aliases: ['پرسه در مه'] },
  { title: 'Aida, I Saw Your Dad Last Night', year: 2004, difficulty: 'hard', aliases: ['دیشب باباتو دیدم آیدا'] },
  { title: 'Djomeh', year: 2000, difficulty: 'hard', aliases: ['جمعه'] },
  { title: 'Niloofar', year: 2008, difficulty: 'hard', aliases: ['نیلوفر'] },
  { title: 'One Night', year: 2005, difficulty: 'hard', aliases: ['یک شب'] },
  { title: 'The Chess Game of the Wind', year: 1976, difficulty: 'hard', aliases: ['شطرنج باد'] },
  { title: 'The Deserted Station', year: 2002, difficulty: 'hard', aliases: ['ایستگاه متروک'] },
  { title: 'The Wind Carpet', year: 2003, difficulty: 'hard', aliases: ['فرش باد'] },
  { title: 'Willow and Wind', year: 2000, difficulty: 'hard', aliases: ['بید و باد'] },
]

/**
 * Excluded from the game (see notes in git history or prior candidate list):
 * documentaries, foreign co-productions, anthologies, experimental films,
 * and titles too obscure for trailer-guessing gameplay.
 */
