/**
 * Curated movie pool. Difficulty is hand-assigned by how widely recognised the
 * film is, which is a better signal than trailer view count.
 */

export const MOVIES = [
  // ---------- EASY: household-name blockbusters ----------
  { title: 'Avengers: Endgame', year: 2019, difficulty: 'easy' },
  { title: 'The Avengers', year: 2012, difficulty: 'easy' },
  { title: 'Avatar', year: 2009, difficulty: 'easy' },
  { title: 'Titanic', year: 1997, difficulty: 'easy' },
  { title: 'The Dark Knight', year: 2008, difficulty: 'easy' },
  { title: 'Inception', year: 2010, difficulty: 'easy' },
  { title: 'Interstellar', year: 2014, difficulty: 'easy' },
  { title: 'The Matrix', year: 1999, difficulty: 'easy' },
  { title: 'Jurassic Park', year: 1993, difficulty: 'easy' },
  { title: 'The Lion King', year: 1994, difficulty: 'easy' },
  { title: 'Frozen', year: 2013, difficulty: 'easy' },
  { title: 'Toy Story', year: 1995, difficulty: 'easy' },
  { title: 'Finding Nemo', year: 2003, difficulty: 'easy' },
  { title: 'Shrek', year: 2001, difficulty: 'easy' },
  { title: 'The Incredibles', year: 2004, difficulty: 'easy' },
  { title: 'Despicable Me', year: 2010, difficulty: 'easy' },
  { title: 'Harry Potter and the Sorcerer\u2019s Stone', year: 2001, difficulty: 'easy' },
  { title: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001, difficulty: 'easy' },
  { title: 'Star Wars: The Force Awakens', year: 2015, difficulty: 'easy' },
  { title: 'Spider-Man: No Way Home', year: 2021, difficulty: 'easy' },
  { title: 'Black Panther', year: 2018, difficulty: 'easy' },
  { title: 'Iron Man', year: 2008, difficulty: 'easy' },
  { title: 'Deadpool', year: 2016, difficulty: 'easy' },
  { title: 'Joker', year: 2019, difficulty: 'easy' },
  { title: 'Barbie', year: 2023, difficulty: 'easy' },
  { title: 'Oppenheimer', year: 2023, difficulty: 'easy' },
  { title: 'Top Gun: Maverick', year: 2022, difficulty: 'easy' },
  { title: 'Gladiator', year: 2000, difficulty: 'easy' },
  { title: 'Forrest Gump', year: 1994, difficulty: 'easy' },
  { title: 'Back to the Future', year: 1985, difficulty: 'easy' },
  { title: 'Jaws', year: 1975, difficulty: 'easy' },
  { title: 'E.T. the Extra-Terrestrial', year: 1982, difficulty: 'easy' },
  { title: 'Home Alone', year: 1990, difficulty: 'easy' },
  { title: 'Pirates of the Caribbean: The Curse of the Black Pearl', year: 2003, difficulty: 'easy' },
  { title: 'The Hunger Games', year: 2012, difficulty: 'easy' },
  { title: 'Transformers', year: 2007, difficulty: 'easy' },
  { title: 'Twilight', year: 2008, difficulty: 'easy' },
  { title: 'Furious 7', year: 2015, difficulty: 'easy' },
  { title: 'Minions', year: 2015, difficulty: 'easy' },
  { title: 'Moana', year: 2016, difficulty: 'easy' },
  { title: 'Coco', year: 2017, difficulty: 'easy' },
  { title: 'Up', year: 2009, difficulty: 'easy' },
  { title: 'WALL-E', year: 2008, difficulty: 'easy' },
  { title: 'Ratatouille', year: 2007, difficulty: 'easy' },
  { title: 'Inside Out', year: 2015, difficulty: 'easy' },

  // ---------- MEDIUM: widely known, not universal ----------
  { title: 'Pulp Fiction', year: 1994, difficulty: 'medium' },
  { title: 'Fight Club', year: 1999, difficulty: 'medium' },
  { title: 'The Shawshank Redemption', year: 1994, difficulty: 'medium' },
  { title: 'Goodfellas', year: 1990, difficulty: 'medium' },
  { title: 'The Godfather', year: 1972, difficulty: 'medium' },
  { title: 'Parasite', year: 2019, difficulty: 'medium' },
  { title: 'Whiplash', year: 2014, difficulty: 'medium' },
  { title: 'Django Unchained', year: 2012, difficulty: 'medium' },
  { title: 'Inglourious Basterds', year: 2009, difficulty: 'medium' },
  { title: 'The Departed', year: 2006, difficulty: 'medium' },
  { title: 'No Country for Old Men', year: 2007, difficulty: 'medium' },
  { title: 'There Will Be Blood', year: 2007, difficulty: 'medium' },
  { title: 'Mad Max: Fury Road', year: 2015, difficulty: 'medium' },
  { title: 'Blade Runner 2049', year: 2017, difficulty: 'medium' },
  { title: 'Arrival', year: 2016, difficulty: 'medium' },
  { title: 'Get Out', year: 2017, difficulty: 'medium' },
  { title: 'La La Land', year: 2016, difficulty: 'medium' },
  { title: 'Dune', year: 2021, difficulty: 'medium' },
  { title: 'Everything Everywhere All at Once', year: 2022, difficulty: 'medium' },
  { title: 'Knives Out', year: 2019, difficulty: 'medium' },
  { title: '1917', year: 2019, difficulty: 'medium' },
  { title: 'The Wolf of Wall Street', year: 2013, difficulty: 'medium' },
  { title: 'Shutter Island', year: 2010, difficulty: 'medium' },
  { title: 'Prisoners', year: 2013, difficulty: 'medium' },
  { title: 'Gone Girl', year: 2014, difficulty: 'medium' },
  { title: 'The Social Network', year: 2010, difficulty: 'medium' },
  { title: 'Birdman', year: 2014, difficulty: 'medium' },
  { title: 'The Grand Budapest Hotel', year: 2014, difficulty: 'medium' },
  { title: 'Her', year: 2013, difficulty: 'medium' },
  { title: 'Ex Machina', year: 2014, difficulty: 'medium' },
  { title: 'Sicario', year: 2015, difficulty: 'medium' },
  { title: 'Nightcrawler', year: 2014, difficulty: 'medium' },
  { title: 'Drive', year: 2011, difficulty: 'medium' },
  { title: 'Memento', year: 2000, difficulty: 'medium' },
  { title: 'Se7en', year: 1995, difficulty: 'medium' },
  { title: 'The Silence of the Lambs', year: 1991, difficulty: 'medium' },
  { title: 'American Psycho', year: 2000, difficulty: 'medium' },
  { title: 'Requiem for a Dream', year: 2000, difficulty: 'medium' },
  { title: 'Eternal Sunshine of the Spotless Mind', year: 2004, difficulty: 'medium' },
  { title: 'Moonlight', year: 2016, difficulty: 'medium' },
  { title: 'Green Book', year: 2018, difficulty: 'medium' },
  { title: 'Bohemian Rhapsody', year: 2018, difficulty: 'medium' },
  { title: 'A Star Is Born', year: 2018, difficulty: 'medium' },
  { title: 'Us', year: 2019, difficulty: 'medium' },
  { title: 'Hereditary', year: 2018, difficulty: 'medium' },
  { title: 'Midsommar', year: 2019, difficulty: 'medium' },
  { title: 'The Witch', year: 2015, difficulty: 'medium' },
  { title: 'It Follows', year: 2014, difficulty: 'medium' },
  { title: 'Train to Busan', year: 2016, difficulty: 'medium' },
  { title: 'Oldboy', year: 2003, difficulty: 'medium' },
  { title: 'Spirited Away', year: 2001, difficulty: 'medium' },
  { title: 'Your Name', year: 2016, difficulty: 'medium' },
  { title: 'Casino Royale', year: 2006, difficulty: 'medium' },
  { title: 'Skyfall', year: 2012, difficulty: 'medium' },
  { title: 'John Wick', year: 2014, difficulty: 'medium' },
  { title: 'Baby Driver', year: 2017, difficulty: 'medium' },
  { title: 'The Revenant', year: 2015, difficulty: 'medium' },
  { title: 'Zodiac', year: 2007, difficulty: 'medium' },

  // ---------- HARD: arthouse, festival, international ----------
  { title: 'The Lighthouse', year: 2019, difficulty: 'hard' },
  { title: 'Aftersun', year: 2022, difficulty: 'hard' },
  { title: 'Past Lives', year: 2023, difficulty: 'hard' },
  { title: 'The Zone of Interest', year: 2023, difficulty: 'hard' },
  { title: 'Anora', year: 2024, difficulty: 'hard' },
  { title: 'Nomadland', year: 2020, difficulty: 'hard' },
  { title: 'The Banshees of Inisherin', year: 2022, difficulty: 'hard' },
  { title: 'Portrait of a Lady on Fire', year: 2019, difficulty: 'hard' },
  { title: 'Burning', year: 2018, difficulty: 'hard' },
  { title: 'The Handmaiden', year: 2016, difficulty: 'hard' },
  { title: 'Under the Skin', year: 2013, difficulty: 'hard' },
  { title: 'The Master', year: 2012, difficulty: 'hard' },
  { title: 'Phantom Thread', year: 2017, difficulty: 'hard' },
  { title: 'Uncut Gems', year: 2019, difficulty: 'hard' },
  { title: 'Good Time', year: 2017, difficulty: 'hard' },
  { title: 'The Florida Project', year: 2017, difficulty: 'hard' },
  { title: 'Lady Bird', year: 2017, difficulty: 'hard' },
  { title: 'Call Me by Your Name', year: 2017, difficulty: 'hard' },
  { title: 'Roma', year: 2018, difficulty: 'hard' },
  { title: 'Cold War', year: 2018, difficulty: 'hard' },
  { title: 'Shoplifters', year: 2018, difficulty: 'hard' },
  { title: 'Drive My Car', year: 2021, difficulty: 'hard' },
  { title: 'T\u00e1r', year: 2022, difficulty: 'hard' },
  { title: 'Decision to Leave', year: 2022, difficulty: 'hard' },
  { title: 'Triangle of Sadness', year: 2022, difficulty: 'hard' },
  { title: 'The Worst Person in the World', year: 2021, difficulty: 'hard' },
  { title: 'Minari', year: 2020, difficulty: 'hard' },
  { title: 'Sound of Metal', year: 2019, difficulty: 'hard' },
  { title: 'First Reformed', year: 2017, difficulty: 'hard' },
  { title: 'A Ghost Story', year: 2017, difficulty: 'hard' },
  { title: 'Moonrise Kingdom', year: 2012, difficulty: 'hard' },
  { title: 'The Tree of Life', year: 2011, difficulty: 'hard' },
  { title: 'Melancholia', year: 2011, difficulty: 'hard' },
  { title: 'Mulholland Drive', year: 2001, difficulty: 'hard' },
  { title: 'In the Mood for Love', year: 2000, difficulty: 'hard' },
  { title: 'Am\u00e9lie', year: 2001, difficulty: 'hard' },
  { title: 'City of God', year: 2002, difficulty: 'hard' },
  { title: 'Pan\u2019s Labyrinth', year: 2006, difficulty: 'hard' },
  { title: 'The Lives of Others', year: 2006, difficulty: 'hard' },
  { title: 'Let the Right One In', year: 2008, difficulty: 'hard' },
  { title: 'A Separation', year: 2011, difficulty: 'hard' },
  { title: 'The Hunt', year: 2012, difficulty: 'hard' },
  { title: 'Force Majeure', year: 2014, difficulty: 'hard' },
  { title: 'Son of Saul', year: 2015, difficulty: 'hard' },
  { title: 'Toni Erdmann', year: 2016, difficulty: 'hard' },
  { title: 'The Square', year: 2017, difficulty: 'hard' },
  { title: 'Border', year: 2018, difficulty: 'hard' },
  { title: 'Stalker', year: 1979, difficulty: 'hard' },
  { title: 'Come and See', year: 1985, difficulty: 'hard' },
  { title: 'Paris, Texas', year: 1984, difficulty: 'hard' },
]
