export interface MovieSeed {
  title: string
  year: number
  difficulty: 'easy' | 'medium' | 'hard'
  aliases?: string[]
}

/**
 * Curated pool. Difficulty is set by how recognisable the film is from a
 * fraction of a second of its trailer, not by trailer view count.
 */
export const MOVIES: MovieSeed[] = [
  // ---------- EASY: household-name blockbusters ----------
  { title: 'Avengers: Endgame', year: 2019, difficulty: 'easy', aliases: ['endgame'] },
  { title: 'Avengers: Infinity War', year: 2018, difficulty: 'easy', aliases: ['infinity war'] },
  { title: 'The Avengers', year: 2012, difficulty: 'easy', aliases: ['avengers assemble'] },
  { title: 'Iron Man', year: 2008, difficulty: 'easy' },
  { title: 'Black Panther', year: 2018, difficulty: 'easy' },
  { title: 'Spider-Man: No Way Home', year: 2021, difficulty: 'easy', aliases: ['no way home'] },
  { title: 'The Dark Knight', year: 2008, difficulty: 'easy', aliases: ['dark knight'] },
  { title: 'Batman Begins', year: 2005, difficulty: 'easy' },
  { title: 'Joker', year: 2019, difficulty: 'easy' },
  { title: 'Wonder Woman', year: 2017, difficulty: 'easy' },
  { title: 'Man of Steel', year: 2013, difficulty: 'easy' },
  { title: 'Titanic', year: 1997, difficulty: 'easy' },
  { title: 'Avatar', year: 2009, difficulty: 'easy' },
  { title: 'Jurassic Park', year: 1993, difficulty: 'easy' },
  { title: 'Jurassic World', year: 2015, difficulty: 'easy' },
  { title: 'The Lion King', year: 1994, difficulty: 'easy' },
  { title: 'Frozen', year: 2013, difficulty: 'easy' },
  { title: 'Toy Story', year: 1995, difficulty: 'easy' },
  { title: 'Finding Nemo', year: 2003, difficulty: 'easy' },
  { title: 'Shrek', year: 2001, difficulty: 'easy' },
  { title: 'Despicable Me', year: 2010, difficulty: 'easy' },
  { title: 'Minions', year: 2015, difficulty: 'easy' },
  { title: 'Moana', year: 2016, difficulty: 'easy' },
  { title: 'Encanto', year: 2021, difficulty: 'easy' },
  { title: 'Inside Out', year: 2015, difficulty: 'easy' },
  { title: 'Barbie', year: 2023, difficulty: 'easy' },
  { title: 'Oppenheimer', year: 2023, difficulty: 'easy' },
  { title: 'Inception', year: 2010, difficulty: 'easy' },
  { title: 'Interstellar', year: 2014, difficulty: 'easy' },
  { title: 'The Matrix', year: 1999, difficulty: 'easy', aliases: ['matrix'] },
  { title: 'Star Wars: The Force Awakens', year: 2015, difficulty: 'easy', aliases: ['the force awakens'] },
  { title: 'Rogue One: A Star Wars Story', year: 2016, difficulty: 'easy', aliases: ['rogue one'] },
  { title: 'Harry Potter and the Sorcerer\u2019s Stone', year: 2001, difficulty: 'easy', aliases: ['harry potter', 'philosophers stone', 'sorcerers stone'] },
  { title: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001, difficulty: 'easy', aliases: ['fellowship of the ring', 'lord of the rings'] },
  { title: 'Pirates of the Caribbean: The Curse of the Black Pearl', year: 2003, difficulty: 'easy', aliases: ['pirates of the caribbean', 'curse of the black pearl'] },
  { title: 'Top Gun: Maverick', year: 2022, difficulty: 'easy', aliases: ['maverick'] },
  { title: 'Fast Five', year: 2011, difficulty: 'easy' },
  { title: 'Mission: Impossible \u2013 Fallout', year: 2018, difficulty: 'easy', aliases: ['fallout', 'mission impossible fallout'] },
  { title: 'Deadpool', year: 2016, difficulty: 'easy' },
  { title: 'Guardians of the Galaxy', year: 2014, difficulty: 'easy' },
  { title: 'Doctor Strange', year: 2016, difficulty: 'easy' },
  { title: 'Thor: Ragnarok', year: 2017, difficulty: 'easy' },
  { title: 'Captain America: Civil War', year: 2016, difficulty: 'easy', aliases: ['civil war'] },
  { title: 'The Hunger Games', year: 2012, difficulty: 'easy' },
  { title: 'Twilight', year: 2008, difficulty: 'easy' },
  { title: 'Dune', year: 2021, difficulty: 'easy', aliases: ['dune part one'] },
  { title: 'The Wolf of Wall Street', year: 2013, difficulty: 'easy', aliases: ['wolf of wall street'] },
  { title: 'Forrest Gump', year: 1994, difficulty: 'easy' },
  { title: 'The Godfather', year: 1972, difficulty: 'easy', aliases: ['godfather'] },
  { title: 'Pulp Fiction', year: 1994, difficulty: 'easy' },
  { title: 'Gladiator', year: 2000, difficulty: 'easy' },
  { title: 'The Shawshank Redemption', year: 1994, difficulty: 'easy', aliases: ['shawshank'] },
  { title: 'Fight Club', year: 1999, difficulty: 'easy' },
  { title: 'Jaws', year: 1975, difficulty: 'easy' },
  { title: 'Back to the Future', year: 1985, difficulty: 'easy' },
  { title: 'E.T. the Extra-Terrestrial', year: 1982, difficulty: 'easy', aliases: ['et', 'e t'] },
  { title: 'The Terminator', year: 1984, difficulty: 'easy', aliases: ['terminator'] },
  { title: 'Terminator 2: Judgment Day', year: 1991, difficulty: 'easy', aliases: ['terminator 2'] },
  { title: 'Home Alone', year: 1990, difficulty: 'easy' },

  // ---------- MEDIUM: widely seen, less universal ----------
  { title: 'Parasite', year: 2019, difficulty: 'medium', aliases: ['gisaengchung'] },
  { title: 'Whiplash', year: 2014, difficulty: 'medium' },
  { title: 'La La Land', year: 2016, difficulty: 'medium' },
  { title: 'Get Out', year: 2017, difficulty: 'medium' },
  { title: 'Us', year: 2019, difficulty: 'medium' },
  { title: 'Nope', year: 2022, difficulty: 'medium' },
  { title: 'Hereditary', year: 2018, difficulty: 'medium' },
  { title: 'Midsommar', year: 2019, difficulty: 'medium' },
  { title: 'The Witch', year: 2015, difficulty: 'medium', aliases: ['the vvitch'] },
  { title: 'A Quiet Place', year: 2018, difficulty: 'medium' },
  { title: 'It', year: 2017, difficulty: 'medium', aliases: ['it chapter one'] },
  { title: 'The Conjuring', year: 2013, difficulty: 'medium' },
  { title: 'Sinister', year: 2012, difficulty: 'medium' },
  { title: 'Everything Everywhere All at Once', year: 2022, difficulty: 'medium', aliases: ['eeaao', 'everything everywhere'] },
  { title: 'Knives Out', year: 2019, difficulty: 'medium' },
  { title: 'Glass Onion: A Knives Out Mystery', year: 2022, difficulty: 'medium', aliases: ['glass onion'] },
  { title: 'Baby Driver', year: 2017, difficulty: 'medium' },
  { title: 'Drive', year: 2011, difficulty: 'medium' },
  { title: 'Blade Runner 2049', year: 2017, difficulty: 'medium' },
  { title: 'Blade Runner', year: 1982, difficulty: 'medium' },
  { title: 'Arrival', year: 2016, difficulty: 'medium' },
  { title: 'Ex Machina', year: 2014, difficulty: 'medium' },
  { title: 'Her', year: 2013, difficulty: 'medium' },
  { title: 'Gravity', year: 2013, difficulty: 'medium' },
  { title: 'The Martian', year: 2015, difficulty: 'medium' },
  { title: 'Mad Max: Fury Road', year: 2015, difficulty: 'medium', aliases: ['fury road'] },
  { title: 'John Wick', year: 2014, difficulty: 'medium' },
  { title: 'Sicario', year: 2015, difficulty: 'medium' },
  { title: 'Prisoners', year: 2013, difficulty: 'medium' },
  { title: 'Gone Girl', year: 2014, difficulty: 'medium' },
  { title: 'Zodiac', year: 2007, difficulty: 'medium' },
  { title: 'The Social Network', year: 2010, difficulty: 'medium' },
  { title: 'The Departed', year: 2006, difficulty: 'medium' },
  { title: 'Shutter Island', year: 2010, difficulty: 'medium' },
  { title: 'Django Unchained', year: 2012, difficulty: 'medium' },
  { title: 'Inglourious Basterds', year: 2009, difficulty: 'medium' },
  { title: 'Once Upon a Time in Hollywood', year: 2019, difficulty: 'medium' },
  { title: 'Kill Bill: Vol. 1', year: 2003, difficulty: 'medium', aliases: ['kill bill'] },
  { title: 'No Country for Old Men', year: 2007, difficulty: 'medium' },
  { title: 'There Will Be Blood', year: 2007, difficulty: 'medium' },
  { title: 'The Big Lebowski', year: 1998, difficulty: 'medium', aliases: ['big lebowski'] },
  { title: 'The Grand Budapest Hotel', year: 2014, difficulty: 'medium', aliases: ['grand budapest hotel'] },
  { title: 'Moonrise Kingdom', year: 2012, difficulty: 'medium' },
  { title: 'Birdman', year: 2014, difficulty: 'medium' },
  { title: 'The Revenant', year: 2015, difficulty: 'medium' },
  { title: '1917', year: 2019, difficulty: 'medium' },
  { title: 'Dunkirk', year: 2017, difficulty: 'medium' },
  { title: 'Tenet', year: 2020, difficulty: 'medium' },
  { title: 'The Prestige', year: 2006, difficulty: 'medium' },
  { title: 'Memento', year: 2000, difficulty: 'medium' },
  { title: 'Spirited Away', year: 2001, difficulty: 'medium', aliases: ['sen to chihiro'] },
  { title: 'Your Name', year: 2016, difficulty: 'medium', aliases: ['kimi no na wa'] },
  { title: 'Coco', year: 2017, difficulty: 'medium' },
  { title: 'Up', year: 2009, difficulty: 'medium' },
  { title: 'WALL-E', year: 2008, difficulty: 'medium', aliases: ['wall e', 'walle'] },
  { title: 'Ratatouille', year: 2007, difficulty: 'medium' },
  { title: 'Spider-Man: Into the Spider-Verse', year: 2018, difficulty: 'medium', aliases: ['into the spider verse', 'spider verse'] },
  { title: 'Logan', year: 2017, difficulty: 'medium' },
  { title: 'The Batman', year: 2022, difficulty: 'medium' },
  { title: 'Casino Royale', year: 2006, difficulty: 'medium' },
  { title: 'Skyfall', year: 2012, difficulty: 'medium' },

  // ---------- HARD: arthouse, cult, festival ----------
  { title: 'Moonlight', year: 2016, difficulty: 'hard' },
  { title: 'Nomadland', year: 2020, difficulty: 'hard' },
  { title: 'The Lighthouse', year: 2019, difficulty: 'hard', aliases: ['lighthouse'] },
  { title: 'The Banshees of Inisherin', year: 2022, difficulty: 'hard', aliases: ['banshees of inisherin'] },
  { title: 'Aftersun', year: 2022, difficulty: 'hard' },
  { title: 'Past Lives', year: 2023, difficulty: 'hard' },
  { title: 'The Zone of Interest', year: 2023, difficulty: 'hard', aliases: ['zone of interest'] },
  { title: 'Anora', year: 2024, difficulty: 'hard' },
  { title: 'Tar', year: 2022, difficulty: 'hard', aliases: ['t\u00e1r'] },
  { title: 'The Florida Project', year: 2017, difficulty: 'hard' },
  { title: 'Lady Bird', year: 2017, difficulty: 'hard' },
  { title: 'Uncut Gems', year: 2019, difficulty: 'hard' },
  { title: 'Good Time', year: 2017, difficulty: 'hard' },
  { title: 'The Killing of a Sacred Deer', year: 2017, difficulty: 'hard' },
  { title: 'The Lobster', year: 2015, difficulty: 'hard' },
  { title: 'Poor Things', year: 2023, difficulty: 'hard' },
  { title: 'The Favourite', year: 2018, difficulty: 'hard' },
  { title: 'Portrait of a Lady on Fire', year: 2019, difficulty: 'hard' },
  { title: 'Call Me by Your Name', year: 2017, difficulty: 'hard' },
  { title: 'Roma', year: 2018, difficulty: 'hard' },
  { title: 'Burning', year: 2018, difficulty: 'hard' },
  { title: 'Oldboy', year: 2003, difficulty: 'hard' },
  { title: 'The Handmaiden', year: 2016, difficulty: 'hard' },
  { title: 'Drive My Car', year: 2021, difficulty: 'hard' },
  { title: 'Shoplifters', year: 2018, difficulty: 'hard' },
  { title: 'Cold War', year: 2018, difficulty: 'hard' },
  { title: 'The Worst Person in the World', year: 2021, difficulty: 'hard' },
  { title: 'Another Round', year: 2020, difficulty: 'hard' },
  { title: 'Amour', year: 2012, difficulty: 'hard' },
  { title: 'The White Ribbon', year: 2009, difficulty: 'hard' },
  { title: 'Enemy', year: 2013, difficulty: 'hard' },
  { title: 'Under the Skin', year: 2013, difficulty: 'hard' },
  { title: 'Annihilation', year: 2018, difficulty: 'hard' },
  { title: 'Mandy', year: 2018, difficulty: 'hard' },
  { title: 'Climax', year: 2018, difficulty: 'hard' },
  { title: 'Suspiria', year: 2018, difficulty: 'hard' },
  { title: 'The Neon Demon', year: 2016, difficulty: 'hard' },
  { title: 'Only God Forgives', year: 2013, difficulty: 'hard' },
  { title: 'A Ghost Story', year: 2017, difficulty: 'hard' },
  { title: 'First Reformed', year: 2017, difficulty: 'hard' },
  { title: 'Paterson', year: 2016, difficulty: 'hard' },
  { title: 'Columbus', year: 2017, difficulty: 'hard' },
  { title: 'Minari', year: 2020, difficulty: 'hard' },
  { title: 'Sound of Metal', year: 2019, difficulty: 'hard' },
  { title: 'The Rider', year: 2017, difficulty: 'hard' },
  { title: 'Leave No Trace', year: 2018, difficulty: 'hard' },
  { title: 'Beasts of the Southern Wild', year: 2012, difficulty: 'hard' },
  { title: 'Winter\u2019s Bone', year: 2010, difficulty: 'hard', aliases: ['winters bone'] },
  { title: 'Ida', year: 2013, difficulty: 'hard' },
  { title: 'Son of Saul', year: 2015, difficulty: 'hard' },
  { title: 'A Separation', year: 2011, difficulty: 'hard' },
  { title: 'The Square', year: 2017, difficulty: 'hard' },
  { title: 'Force Majeure', year: 2014, difficulty: 'hard' },
  { title: 'Toni Erdmann', year: 2016, difficulty: 'hard' },
  { title: 'Raw', year: 2016, difficulty: 'hard' },
  { title: 'Titane', year: 2021, difficulty: 'hard' },
  { title: 'Saint Maud', year: 2019, difficulty: 'hard' },
  { title: 'The Green Knight', year: 2021, difficulty: 'hard' },
  { title: 'Everything Went Fine', year: 2021, difficulty: 'hard' },
  { title: 'Petite Maman', year: 2021, difficulty: 'hard' },
  { title: 'Am\u00e9lie', year: 2001, difficulty: 'hard', aliases: ['amelie'] },
  { title: 'Mulholland Drive', year: 2001, difficulty: 'hard' },
  { title: 'In the Mood for Love', year: 2000, difficulty: 'hard' },
  { title: 'Pan\u2019s Labyrinth', year: 2006, difficulty: 'hard', aliases: ['pans labyrinth'] },
  { title: 'City of God', year: 2002, difficulty: 'hard', aliases: ['cidade de deus'] },
  { title: 'Let the Right One In', year: 2008, difficulty: 'hard' },
  { title: 'The Lives of Others', year: 2006, difficulty: 'hard' },
  { title: 'Paris, Texas', year: 1984, difficulty: 'hard', aliases: ['paris texas'] },
  { title: 'Stalker', year: 1979, difficulty: 'hard' },
  { title: 'Come and See', year: 1985, difficulty: 'hard' },
  { title: 'The Tree of Life', year: 2011, difficulty: 'hard' },
  { title: 'Melancholia', year: 2011, difficulty: 'hard' },
  { title: 'The Hunt', year: 2012, difficulty: 'hard', aliases: ['jagten'] },
  { title: 'Border', year: 2018, difficulty: 'hard', aliases: ['gr\u00e4ns'] },
]
